export default function handler(req, res) {
  // 只允许GET请求
  if (req.method !== 'GET') {
    return res.status(405).json({ code: 405, msg: "只允许GET请求" })
  }
  
  const data = [
    {
        "id": 1,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*yHnhRL4x1DEAAAAAQBAAAAgAeh6VAQ/original",
        "user": "Suya Xu",
        "tag": "Inbox",
        "property": "GR1",
        "propertyInfo": "#GR1 Light Filled 2 BR Ikebukuro Large Apartment",
        "checkin": "Dec 30 2019",
        "checkout": "Jan 1 2020",
        "desc": "GR1 (12月30日 2019) ~ 1月1日 2020 @airbnb2 ",
        "descDetail": "Can you please restart the device? and try again.",
        "update": "a month ago",
        "starColor": "#f00",
        "archived": false,
        "starred": true
    },
    {
        "id": 2,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*Z4-4Q67SG5UAAAAAQLAAAAgAeh6VAQ/original",
        "user": "Stanley",
        "tag": "Inbox",
        "property": "2M11",
        "propertyInfo": "",
        "checkin": "Feb 15 2020",
        "checkout": "Feb 15 2020",
        "desc": "Airbnb2 Inquiry:Stanley",
        "descDetail": "Yes,it on basement without windows but there's ventilation fan.There's an elevator as well as stairs going to the room.",
        "update": "2 month ago",
        "starColor": "#d4ff00",
        "archived": false,
        "starred": false
    },
    {
        "id": 3,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*SXcuQYBZ6oQAAAAAQJAAAAgAeh6VAQ/original",
        "user": "Suya Xu",
        "tag": "Inbox",
        "property": "GR1",
        "propertyInfo": "#GR1 Light Filled 2 BR Ikebukuro Large Apartment",
        "checkin": "Dec 30 2019",
        "checkout": "Jan 1 2020",
        "desc": "GR1 (12月30日 2019) ~ 1月1日 2020 @airbnb2 ",
        "descDetail": "Can you please restart the device? and try again.",
        "update": "a month ago",
        "starColor": "#20ff03",
        "archived": false,
        "starred": true
    },
    {
        "id": 4,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*yHnhRL4x1DEAAAAAQBAAAAgAeh6VAQ/original",
        "user": "Suya Xu",
        "tag": "Inbox",
        "property": "GR1",
        "propertyInfo": "#GR1 Light Filled 2 BR Ikebukuro Large Apartment",
        "checkin": "Dec 30 2019",
        "checkout": "Jan 1 2020",
        "desc": "GR1 (12月30日 2019) ~ 1月1日 2020 @airbnb2 ",
        "descDetail": "Can you please restart the device? and try again.",
        "update": "a month ago",
        "starColor": "#007bff",
        "archived": false,
        "starred": true
    },
    {
        "id": 5,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*yHnhRL4x1DEAAAAAQBAAAAgAeh6VAQ/original",
        "user": "Mike Chen",
        "tag": "Inbox",
        "property": "GR1",
        "propertyInfo": "#GR1 Light Filled 2 BR Ikebukuro Large Apartment",
        "checkin": "Mar 10 2020",
        "checkout": "Mar 14 2020",
        "desc": "GR1 (3月10日 2020) ~ 3月14日 2020 @airbnb2",
        "descDetail": "Hi, is there a hair dryer in the apartment? We will arrive late at night.",
        "update": "3 days ago",
        "starColor": "#ff6b00",
        "archived": false,
        "starred": false
    },
    {
        "id": 6,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*Z4-4Q67SG5UAAAAAQLAAAAgAeh6VAQ/original",
        "user": "Lisa Wang",
        "tag": "Inbox",
        "property": "GR1",
        "propertyInfo": "#GR1 Light Filled 2 BR Ikebukuro Large Apartment",
        "checkin": "Apr 05 2020",
        "checkout": "Apr 08 2020",
        "desc": "GR1 (4月5日 2020) ~ 4月8日 2020 @booking",
        "descDetail": "The WiFi password doesn't work. Can you send me the correct one?",
        "update": "a week ago",
        "starColor": "#9c27b0",
        "archived": false,
        "starred": true
    },
    {
        "id": 7,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*SXcuQYBZ6oQAAAAAQJAAAAgAeh6VAQ/original",
        "user": "Tom Brown",
        "tag": "Inbox",
        "property": "GR1",
        "propertyInfo": "#GR1 Light Filled 2 BR Ikebukuro Large Apartment",
        "checkin": "May 20 2020",
        "checkout": "May 25 2020",
        "desc": "GR1 (5月20日 2020) ~ 5月25日 2020 @airbnb2",
        "descDetail": "We had a great stay! Just wanted to ask if you offer long-term discounts?",
        "update": "2 weeks ago",
        "starColor": "#00bcd4",
        "archived": false,
        "starred": false
    },
    {
        "id": 8,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*yHnhRL4x1DEAAAAAQBAAAAgAeh6VAQ/original",
        "user": "Anna Lee",
        "tag": "Inbox",
        "property": "GR1",
        "propertyInfo": "#GR1 Light Filled 2 BR Ikebukuro Large Apartment",
        "checkin": "Jun 15 2020",
        "checkout": "Jun 18 2020",
        "desc": "GR1 (6月15日 2020) ~ 6月18日 2020 @airbnb2",
        "descDetail": "Is there parking available nearby? We are renting a car during our stay.",
        "update": "5 days ago",
        "starColor": "#e91e63",
        "archived": true,
        "starred": true
    },
    {
        "id": 9,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*Z4-4Q67SG5UAAAAAQLAAAAgAeh6VAQ/original",
        "user": "David Kim",
        "tag": "Inbox",
        "property": "2M11",
        "propertyInfo": "",
        "checkin": "Jan 08 2020",
        "checkout": "Jan 10 2020",
        "desc": "2M11 (1月8日 2020) ~ 1月10日 2020 @airbnb2",
        "descDetail": "How do I access the building? Is there a key box or do I need to meet you?",
        "update": "3 weeks ago",
        "starColor": "#ffc107",
        "archived": false,
        "starred": false
    },
    {
        "id": 10,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*SXcuQYBZ6oQAAAAAQJAAAAgAeh6VAQ/original",
        "user": "Emma Wilson",
        "tag": "Inbox",
        "property": "2M11",
        "propertyInfo": "",
        "checkin": "Feb 22 2020",
        "checkout": "Feb 25 2020",
        "desc": "2M11 (2月22日 2020) ~ 2月25日 2020 @booking",
        "descDetail": "The heater seems broken, the room is very cold. Can someone come fix it?",
        "update": "1 month ago",
        "starColor": "#8bc34a",
        "archived": false,
        "starred": true
    },
    {
        "id": 11,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*yHnhRL4x1DEAAAAAQBAAAAgAeh6VAQ/original",
        "user": "Jack Zhang",
        "tag": "Inbox",
        "property": "2M11",
        "propertyInfo": "",
        "checkin": "Mar 30 2020",
        "checkout": "Apr 02 2020",
        "desc": "2M11 (3月30日 2020) ~ 4月2日 2020 @airbnb2",
        "descDetail": "Can we check out an hour later? Our flight is at 6pm.",
        "update": "4 days ago",
        "starColor": "#ff5722",
        "archived": false,
        "starred": false
    },
    {
        "id": 12,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*Z4-4Q67SG5UAAAAAQLAAAAgAeh6VAQ/original",
        "user": "Sophie Martin",
        "tag": "Inbox",
        "property": "3A5",
        "propertyInfo": "#3A5 Cozy Studio Near Shinjuku Station",
        "checkin": "Jan 15 2020",
        "checkout": "Jan 20 2020",
        "desc": "3A5 (1月15日 2020) ~ 1月20日 2020 @airbnb2",
        "descDetail": "Is the apartment smoking-friendly? My friend is a smoker.",
        "update": "2 months ago",
        "starColor": "#3f51b5",
        "archived": false,
        "starred": true
    },
    {
        "id": 13,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*SXcuQYBZ6oQAAAAAQJAAAAgAeh6VAQ/original",
        "user": "Ryan Taylor",
        "tag": "Inbox",
        "property": "3A5",
        "propertyInfo": "#3A5 Cozy Studio Near Shinjuku Station",
        "checkin": "Feb 28 2020",
        "checkout": "Mar 03 2020",
        "desc": "3A5 (2月28日 2020) ~ 3月3日 2020 @booking",
        "descDetail": "We found the key but the door is stuck. Can you guide us how to open it?",
        "update": "6 days ago",
        "starColor": "#009688",
        "archived": false,
        "starred": false
    },
    {
        "id": 14,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*yHnhRL4x1DEAAAAAQBAAAAgAeh6VAQ/original",
        "user": "Olivia Park",
        "tag": "Inbox",
        "property": "3A5",
        "propertyInfo": "#3A5 Cozy Studio Near Shinjuku Station",
        "checkin": "Apr 18 2020",
        "checkout": "Apr 22 2020",
        "desc": "3A5 (4月18日 2020) ~ 4月22日 2020 @airbnb2",
        "descDetail": "Thank you for the stay! The location was perfect. Do you have other properties?",
        "update": "3 weeks ago",
        "starColor": "#795548",
        "archived": false,
        "starred": true
    },
    {
        "id": 15,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*Z4-4Q67SG5UAAAAAQLAAAAgAeh6VAQ/original",
        "user": "Kevin Liu",
        "tag": "Inbox",
        "property": "4B2",
        "propertyInfo": "#4B2 Modern 1BR in Shibuya Center",
        "checkin": "May 05 2020",
        "checkout": "May 09 2020",
        "desc": "4B2 (5月5日 2020) ~ 5月9日 2020 @airbnb2",
        "descDetail": "Is there a washing machine in the unit? We are staying for 4 nights.",
        "update": "1 week ago",
        "starColor": "#607d8b",
        "archived": true,
        "starred": false
    },
    {
        "id": 16,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*SXcuQYBZ6oQAAAAAQJAAAAgAeh6VAQ/original",
        "user": "Rachel Green",
        "tag": "Inbox",
        "property": "4B2",
        "propertyInfo": "#4B2 Modern 1BR in Shibuya Center",
        "checkin": "Jun 22 2020",
        "checkout": "Jun 26 2020",
        "desc": "4B2 (6月22日 2020) ~ 6月26日 2020 @booking",
        "descDetail": "The AC is not cooling properly. Can you check the remote settings?",
        "update": "2 days ago",
        "starColor": "#ff9800",
        "archived": false,
        "starred": true
    },
    {
        "id": 17,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*yHnhRL4x1DEAAAAAQBAAAAgAeh6VAQ/original",
        "user": "Chris Evans",
        "tag": "Inbox",
        "property": "5C8",
        "propertyInfo": "#5C8 Traditional Tatami House in Asakusa",
        "checkin": "Jul 10 2020",
        "checkout": "Jul 15 2020",
        "desc": "5C8 (7月10日 2020) ~ 7月15日 2020 @airbnb2",
        "descDetail": "We love the tatami room! Is it okay to eat on the floor mats?",
        "update": "5 days ago",
        "starColor": "#4caf50",
        "archived": true,
        "starred": false
    },
    {
        "id": 18,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*Z4-4Q67SG5UAAAAAQLAAAAgAeh6VAQ/original",
        "user": "Natalie Port",
        "tag": "Inbox",
        "property": "5C8",
        "propertyInfo": "#5C8 Traditional Tatami House in Asakusa",
        "checkin": "Aug 01 2020",
        "checkout": "Aug 05 2020",
        "desc": "5C8 (8月1日 2020) ~ 8月5日 2020 @airbnb2",
        "descDetail": "Can you recommend a good sushi restaurant within walking distance?",
        "update": "1 day ago",
        "starColor": "#e91e63",
        "archived": false,
        "starred": true
    },
    {
        "id": 19,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*SXcuQYBZ6oQAAAAAQJAAAAgAeh6VAQ/original",
        "user": "Daniel Wu",
        "tag": "Inbox",
        "property": "6D3",
        "propertyInfo": "#6D3 Compact Apartment Ueno Area",
        "checkin": "Sep 12 2020",
        "checkout": "Sep 16 2020",
        "desc": "6D3 (9月12日 2020) ~ 9月16日 2020 @booking",
        "descDetail": "We lost the key card. Is there a spare one or do we need to pay for replacement?",
        "update": "4 days ago",
        "starColor": "#2196f3",
        "archived": false,
        "starred": false
    },
    {
        "id": 20,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*yHnhRL4x1DEAAAAAQBAAAAgAeh6VAQ/original",
        "user": "Mia Chen",
        "tag": "Inbox",
        "property": "6D3",
        "propertyInfo": "#6D3 Compact Apartment Ueno Area",
        "checkin": "Oct 08 2020",
        "checkout": "Oct 12 2020",
        "desc": "6D3 (10月8日 2020) ~ 10月12日 2020 @airbnb2",
        "descDetail": "Is there an elevator in the building? We have heavy luggage.",
        "update": "2 weeks ago",
        "starColor": "#ffeb3b",
        "archived": false,
        "starred": true
    },
    {
        "id": 21,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*Z4-4Q67SG5UAAAAAQLAAAAgAeh6VAQ/original",
        "user": "James Bond",
        "tag": "Inbox",
        "property": "7E9",
        "propertyInfo": "#7E9 Luxury Penthouse Roppongi Hills",
        "checkin": "Nov 20 2020",
        "checkout": "Nov 25 2020",
        "desc": "7E9 (11月20日 2020) ~ 11月25日 2020 @airbnb2",
        "descDetail": "Do you provide airport pickup service? We arrive at Narita at 9am.",
        "update": "3 days ago",
        "starColor": "#9c27b0",
        "archived": false,
        "starred": false
    },
    {
        "id": 22,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*SXcuQYBZ6oQAAAAAQJAAAAgAeh6VAQ/original",
        "user": "Scarlett Johansson",
        "tag": "Inbox",
        "property": "7E9",
        "propertyInfo": "#7E9 Luxury Penthouse Roppongi Hills",
        "checkin": "Dec 15 2020",
        "checkout": "Dec 20 2020",
        "desc": "7E9 (12月15日 2020) ~ 12月20日 2020 @booking",
        "descDetail": "The view is amazing! Can we have an extra blanket? It gets cold at night.",
        "update": "1 week ago",
        "starColor": "#00bcd4",
        "archived": false,
        "starred": true
    },
    {
        "id": 23,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*yHnhRL4x1DEAAAAAQBAAAAgAeh6VAQ/original",
        "user": "Robert Downey",
        "tag": "Inbox",
        "property": "8F1",
        "propertyInfo": "#8F1 Budget Room Near Akihabara",
        "checkin": "Jan 05 2021",
        "checkout": "Jan 08 2021",
        "desc": "8F1 (1月5日 2021) ~ 1月8日 2021 @airbnb2",
        "descDetail": "Is there a convenience store nearby? We need to buy some snacks.",
        "update": "6 days ago",
        "starColor": "#8bc34a",
        "archived": false,
        "starred": false
    },
    {
        "id": 24,
        "avatar": "https://mdn.alipayobjects.com/huamei_vmgq1x/afts/img/A*Z4-4Q67SG5UAAAAAQLAAAAgAeh6VAQ/original",
        "user": "Zoe Saldana",
        "tag": "Inbox",
        "property": "GR1",
        "propertyInfo": "#GR1 Light Filled 2 BR Ikebukuro Large Apartment",
        "checkin": "Feb 14 2021",
        "checkout": "Feb 17 2021",
        "desc": "GR1 (2月14日 2021) ~ 2月17日 2021 @airbnb2",
        "descDetail": "Happy Valentine's Day! Do you have any special recommendations for couples?",
        "update": "2 days ago",
        "starColor": "#f44336",
        "archived": false,
        "starred": true
    }
    ]

  res.status(200).json(data)
}
